// This file is auto-generated. Do not edit manually.
// Run 'npm run auto-import-components' to update.

import {Repos} from '../../../types/common';
import {Component} from '../types';
import {createComponentConfig} from '../utils';

export const autoGeneratedComponents: Component[] = ([] as string[]).map((name) =>
    createComponentConfig(name, Repos.Uikit),
);
