export const libs = [
    {
        id: 'uikit',
        githubId: 'gravity-ui/uikit',
        npmId: '@gravity-ui/uikit',
        title: 'UIKit',
        primary: true,
        landing: true,
        tags: ['ui'],
        description: {
            en: 'Base UI components and tokens for building services with Gravity.',
            ru: 'Базовые UI компоненты и токены для построения сервисов с Gravity.',
        },
        storybookUrl: 'https://preview.gravity-ui.com/uikit/',
        readmeUrl: 'https://raw.githubusercontent.com/gravity-ui/uikit/main/README.md',
        changelogUrl: 'https://raw.githubusercontent.com/gravity-ui/uikit/main/CHANGELOG.md',
        mainBranch: 'main',
    },
    {
        id: 'components',
        githubId: 'gravity-ui/components',
        npmId: '@gravity-ui/components',
        title: 'Components',
        primary: false,
        landing: false,
        tags: ['ui'],
        description: {
            en: 'A set of complex React components.',
            ru: 'Набор комлпексных React компонентов.',
        },
        storybookUrl:
            'https://preview.gravity-ui.com/components/?path=/story/components-adaptivetabs--default',
        readmeUrl: 'https://raw.githubusercontent.com/gravity-ui/components/main/README.md',
        changelogUrl: 'https://raw.githubusercontent.com/gravity-ui/components/main/CHANGELOG.md',
        mainBranch: 'main',
    },
    {
        id: 'icons',
        githubId: 'gravity-ui/icons',
        npmId: '@gravity-ui/icons',
        title: 'Icons',
        primary: false,
        landing: false,
        tags: ['ui'],
        description: {
            en: 'Set with hundreds of various modern SVG icons for your projects.',
            ru: 'Набор сотен разнообразных современных иконок для ваших проектов.',
        },
        storybookUrl: 'https://preview.gravity-ui.com/icons/',
        readmeUrl: 'https://raw.githubusercontent.com/gravity-ui/icons/main/README.md',
        changelogUrl: 'https://raw.githubusercontent.com/gravity-ui/icons/main/CHANGELOG.md',
        mainBranch: 'main',
    },
    {
        id: 'dynamic-forms',
        githubId: 'gravity-ui/dynamic-forms',
        npmId: '@gravity-ui/dynamic-forms',
        title: 'Dynamic Forms',
        primary: false,
        landing: false,
        tags: ['ui'],
        description: {
            en: 'Library for rendering neat and functional react forms described by JSON schema',
            ru: 'Library for rendering neat and functional react forms described by JSON schema',
        },
        storybookUrl: 'https://preview.gravity-ui.com/dynamic-forms/',
        readmeUrl: 'https://raw.githubusercontent.com/gravity-ui/dynamic-forms/main/README.md',
        changelogUrl:
            'https://raw.githubusercontent.com/gravity-ui/dynamic-forms/main/CHANGELOG.md',
        mainBranch: 'main',
    },
    {
        id: 'page-constructor',
        githubId: 'gravity-ui/page-constructor',
        npmId: '@gravity-ui/page-constructor',
        title: 'Page constructor',
        primary: false,
        landing: true,
        tags: ['ui'],
        description: {
            en: 'A set of stylish, functional blocks for quickly creating promo and landing pages.',
            ru: 'Набор стилизованных, функциональных блоков для быстрого создания промо страниц.',
        },
        storybookUrl: 'https://preview.gravity-ui.com/page-constructor/',
        readmeUrl: 'https://raw.githubusercontent.com/gravity-ui/page-constructor/main/README.md',
        changelogUrl:
            'https://raw.githubusercontent.com/gravity-ui/page-constructor/main/CHANGELOG.md',
        mainBranch: 'main',
    },
    {
        id: 'blog-constructor',
        githubId: 'gravity-ui/blog-constructor',
        npmId: '@gravity-ui/blog-constructor',
        title: 'Blog Constructor',
        primary: false,
        landing: false,
        tags: ['ui'],
        description: {
            en: 'A library based on the Page constructor library for creating blog-like services.',
            ru: 'A library based on the Page constructor library for creating blog-like services.',
        },
        storybookUrl: 'https://preview.yandexcloud.dev/blog-constructor/',
        readmeUrl: 'https://raw.githubusercontent.com/gravity-ui/blog-constructor/main/README.md',
        changelogUrl:
            'https://raw.githubusercontent.com/gravity-ui/blog-constructor/main/CHANGELOG.md',
        mainBranch: 'main',
    },
    {
        id: 'chartkit',
        githubId: 'gravity-ui/chartkit',
        npmId: '@gravity-ui/chartkit',
        title: 'ChartKit',
        primary: false,
        landing: true,
        tags: ['ui'],
        description: {
            en: 'A data visualization suite integrated with our design system.',
            ru: 'Пакет визуализации данных, интегрированный с нашей дизайн системой.',
        },
        storybookUrl: '',
        readmeUrl: 'https://raw.githubusercontent.com/gravity-ui/chartkit/main/README.md',
        changelogUrl: 'https://raw.githubusercontent.com/gravity-ui/chartkit/main/CHANGELOG.md',
        mainBranch: 'main',
    },
    {
        id: 'dashkit',
        githubId: 'gravity-ui/dashkit',
        npmId: '@gravity-ui/dashkit',
        title: 'DashKit',
        primary: false,
        landing: true,
        tags: ['ui'],
        description: {
            en: 'A grid component for building interactive dashboards.',
            ru: 'Компонент сетка для построения интерактивных дашбордов.',
        },
        storybookUrl: '',
        readmeUrl: 'https://raw.githubusercontent.com/gravity-ui/dashkit/main/README.md',
        changelogUrl: 'https://raw.githubusercontent.com/gravity-ui/dashkit/main/CHANGELOG.md',
        mainBranch: 'main',
    },
    {
        id: 'yagr',
        githubId: 'gravity-ui/yagr',
        npmId: '@gravity-ui/yagr',
        title: 'Yagr',
        primary: false,
        landing: true,
        tags: ['ui'],
        description: {
            en: 'A high-performance canvas charts renderer, based on uPlot.',
            ru: 'Высокопроизводительная отрисовка canvas графиков, основано на uPlot.',
        },
        storybookUrl: '',
        readmeUrl: 'https://raw.githubusercontent.com/gravity-ui/yagr/main/README.md',
        changelogUrl: 'https://raw.githubusercontent.com/gravity-ui/yagr/main/CHANGELOG.md',
        mainBranch: 'main',
    },
    {
        id: 'nodekit',
        githubId: 'gravity-ui/nodekit',
        npmId: '@gravity-ui/nodekit',
        title: 'NodeKit',
        primary: false,
        landing: false,
        tags: ['nodejs'],
        description: {
            en: 'A simple toolkit for your Node.js apps, scripts and libraries.',
            ru: 'A simple toolkit for your Node.js apps, scripts and libraries.',
        },
        storybookUrl: '',
        readmeUrl: 'https://raw.githubusercontent.com/gravity-ui/nodekit/main/README.md',
        changelogUrl: 'https://raw.githubusercontent.com/gravity-ui/nodekit/main/CHANGELOG.md',
        mainBranch: 'main',
    },
    {
        id: 'expresskit',
        githubId: 'gravity-ui/expresskit',
        npmId: '@gravity-ui/expresskit',
        title: 'ExpressKit',
        primary: false,
        landing: false,
        tags: ['nodejs'],
        description: {
            en: 'Lightweight express.js wrapper that integrates with NodeKit.',
            ru: 'Lightweight express.js wrapper that integrates with NodeKit.',
        },
        storybookUrl: '',
        readmeUrl: 'https://raw.githubusercontent.com/gravity-ui/expresskit/main/README.md',
        changelogUrl: 'https://raw.githubusercontent.com/gravity-ui/expresskit/main/CHANGELOG.md',
        mainBranch: 'main',
    },
    {
        id: 'app-layout',
        githubId: 'gravity-ui/app-layout',
        npmId: '@gravity-ui/app-layout',
        title: 'App Layout',
        primary: false,
        landing: false,
        tags: ['nodejs'],
        description: {
            en: 'HTML layout generator used in our SPA applications.',
            ru: 'HTML layout generator used in our SPA applications.',
        },
        storybookUrl: '',
        readmeUrl: 'https://raw.githubusercontent.com/gravity-ui/app-layout/main/README.md',
        changelogUrl: 'https://raw.githubusercontent.com/gravity-ui/app-layout/main/CHANGELOG.md',
        mainBranch: 'main',
    },
    // {
    //     id: 'app-builder',
    //     githubId: 'gravity-ui/app-builder',
    //     npmId: '@gravity-ui/app-builder',
    //     title: 'App Builder',
    //     primary: false,
    //     landing: false,
    //     tags: ['infrastructure'],
    //     description: {
    //         en: 'Webpack-based static assets builder used in our SPA applications',
    //         ru: 'Webpack-based static assets builder used in our SPA applications',
    //     },
    //     storybookUrl: '',
    //     readmeUrl: 'https://raw.githubusercontent.com/gravity-ui/app-builder/main/README.md',
    //     changelogUrl: 'https://raw.githubusercontent.com/gravity-ui/app-builder/main/CHANGELOG.md',
    //     mainBranch: 'main',
    // },
    {
        id: 'navigation',
        githubId: 'gravity-ui/navigation',
        npmId: '@gravity-ui/navigation',
        title: 'Navigation',
        primary: false,
        landing: true,
        tags: ['ui'],
        description: {
            en: 'A compact and extensible navigation panel for complex services.',
            ru: 'Компактная и расширяемая навигационная панель для сложных сервисов.',
        },
        storybookUrl: 'https://preview.gravity-ui.com/navigation/',
        readmeUrl: 'https://raw.githubusercontent.com/gravity-ui/navigation/main/README.md',
        changelogUrl: 'https://raw.githubusercontent.com/gravity-ui/navigation/main/CHANGELOG.md',
        mainBranch: 'main',
    },
    {
        id: 'date-utils',
        githubId: 'gravity-ui/date-utils',
        npmId: '@gravity-ui/date-utils',
        title: 'Date Utils',
        primary: false,
        landing: false,
        tags: ['ui', 'nodejs'],
        description: {
            en: 'Helpers for managing Date and Time values.',
            ru: 'Helpers for managing Date and Time values.',
        },
        storybookUrl: '',
        readmeUrl: 'https://raw.githubusercontent.com/gravity-ui/date-utils/main/README.md',
        changelogUrl: 'https://raw.githubusercontent.com/gravity-ui/date-utils/main/CHANGELOG.md',
        mainBranch: 'main',
    },
    {
        id: 'axios-wrapper',
        githubId: 'gravity-ui/axios-wrapper',
        npmId: '@gravity-ui/axios-wrapper',
        title: 'Axios wrapper',
        primary: false,
        landing: false,
        tags: ['ui', 'nodejs'],
        description: {
            en: 'Axios wrapper that provides automatic cancelling of concurrent requests.',
            ru: 'Axios wrapper that provides automatic cancelling of concurrent requests.',
        },
        storybookUrl: '',
        readmeUrl: 'https://raw.githubusercontent.com/gravity-ui/axios-wrapper/main/README.md',
        changelogUrl:
            'https://raw.githubusercontent.com/gravity-ui/axios-wrapper/main/CHANGELOG.md',
        mainBranch: 'main',
    },
    {
        id: 'dialog-fields',
        githubId: 'gravity-ui/dialog-fields',
        npmId: '@gravity-ui/dialog-fields',
        title: 'Dialog Fields',
        primary: false,
        landing: false,
        tags: ['ui'],
        description: {
            en: 'A react-final-form wrapper that provides some useful high-level components for building forms',
            ru: 'A react-final-form wrapper that provides some useful high-level components for building forms',
        },
        storybookUrl: '',
        readmeUrl: 'https://raw.githubusercontent.com/gravity-ui/dialog-fields/main/README.md',
        changelogUrl:
            'https://raw.githubusercontent.com/gravity-ui/dialog-fields/main/CHANGELOG.md',
        mainBranch: 'main',
    },
    {
        id: 'paranoid',
        githubId: 'gravity-ui/paranoid',
        npmId: '@gravity-ui/paranoid',
        title: 'Paranoid',
        primary: false,
        landing: false,
        tags: ['ui'],
        description: {
            en: 'Cluster topologies visualizator.',
            ru: 'Cluster topologies visualizator.',
        },
        storybookUrl: '',
        readmeUrl: 'https://raw.githubusercontent.com/gravity-ui/paranoid/main/README.md',
        changelogUrl: 'https://raw.githubusercontent.com/gravity-ui/paranoid/main/CHANGELOG.md',
        mainBranch: 'main',
    },
    {
        id: 'react-data-table',
        githubId: 'gravity-ui/react-data-table',
        npmId: '@gravity-ui/react-data-table',
        title: 'React Data Table',
        primary: false,
        landing: false,
        tags: ['ui'],
        description: {
            en: 'A react component for rendering big and complex tables.',
            ru: 'A react component for rendering big and complex tables.',
        },
        storybookUrl: '',
        readmeUrl: 'https://raw.githubusercontent.com/gravity-ui/react-data-table/main/README.md',
        changelogUrl:
            'https://raw.githubusercontent.com/gravity-ui/react-data-table/main/CHANGELOG.md',
        mainBranch: 'main',
    },
    {
        id: 'unipika',
        githubId: 'gravity-ui/unipika',
        npmId: '@gravity-ui/unipika',
        title: 'Unipika',
        primary: false,
        landing: false,
        tags: ['ui', 'nodejs'],
        description: {
            en: 'Data formatting library.',
            ru: 'Data formatting library.',
        },
        storybookUrl: '',
        readmeUrl: 'https://raw.githubusercontent.com/gravity-ui/unipika/main/README.md',
        changelogUrl: 'https://raw.githubusercontent.com/gravity-ui/unipika/main/CHANGELOG.md',
        mainBranch: 'main',
    },
    {
        id: 'ui-logger',
        githubId: 'gravity-ui/ui-logger',
        npmId: '@gravity-ui/ui-logger',
        title: 'UI Logger',
        primary: false,
        landing: false,
        tags: ['ui'],
        description: {
            en: 'Simple client-side logger',
            ru: 'Simple client-side logger',
        },
        storybookUrl: '',
        readmeUrl: 'https://raw.githubusercontent.com/gravity-ui/ui-logger/main/README.md',
        changelogUrl: 'https://raw.githubusercontent.com/gravity-ui/ui-logger/main/CHANGELOG.md',
        mainBranch: 'main',
    },
    {
        id: 'oauth-clients',
        githubId: 'gravity-ui/oauth-clients',
        npmId: '@gravity-ui/oauth-clients',
        title: 'OAuth Clients',
        primary: false,
        landing: false,
        tags: ['ui'],
        description: {
            en: 'Client OAuth library that provides convenient abstraction on top of auth flow',
            ru: 'Client OAuth library that provides convenient abstraction on top of auth flow',
        },
        storybookUrl: '',
        readmeUrl: 'https://raw.githubusercontent.com/gravity-ui/oauth-clients/main/README.md',
        changelogUrl:
            'https://raw.githubusercontent.com/gravity-ui/oauth-clients/main/CHANGELOG.md',
        mainBranch: 'main',
    },
    {
        id: 'i18n',
        githubId: 'gravity-ui/i18n',
        npmId: '@gravity-ui/i18n',
        title: 'I18n',
        primary: false,
        landing: false,
        tags: ['ui'],
        description: {
            en: 'Internationalization helpers of Gravity UI projects.',
            ru: 'Internationalization helpers of Gravity UI projects.',
        },
        storybookUrl: '',
        readmeUrl: 'https://raw.githubusercontent.com/gravity-ui/i18n/main/README.md',
        changelogUrl: 'https://raw.githubusercontent.com/gravity-ui/i18n/main/CHANGELOG.md',
        mainBranch: 'main',
    },
    {
        id: 'eslint-config',
        githubId: 'gravity-ui/eslint-config',
        npmId: '@gravity-ui/eslint-config',
        title: 'ESlint Config',
        primary: false,
        landing: false,
        tags: ['infrastructure'],
        description: {
            en: 'ESLint configuration preset for Gravity UI projects.',
            ru: 'ESLint configuration preset for Gravity UI projects.',
        },
        storybookUrl: '',
        readmeUrl: 'https://raw.githubusercontent.com/gravity-ui/eslint-config/main/README.md',
        changelogUrl:
            'https://raw.githubusercontent.com/gravity-ui/eslint-config/main/CHANGELOG.md',
        mainBranch: 'main',
    },
    {
        id: 'tsconfig',
        githubId: 'gravity-ui/tsconfig',
        npmId: '@gravity-ui/tsconfig',
        title: 'TSconfig',
        primary: false,
        landing: false,
        tags: ['infrastructure'],
        description: {
            en: 'TypeScript compiler configuration preset for Gravity UI projects',
            ru: 'TypeScript compiler configuration preset for Gravity UI projects',
        },
        storybookUrl: '',
        readmeUrl: 'https://raw.githubusercontent.com/gravity-ui/tsconfig/main/README.md',
        changelogUrl: 'https://raw.githubusercontent.com/gravity-ui/tsconfig/main/CHANGELOG.md',
        mainBranch: 'main',
    },
    {
        id: 'prettier-config',
        githubId: 'gravity-ui/prettier-config',
        npmId: '@gravity-ui/prettier-config',
        title: 'Prettier Config',
        primary: false,
        landing: false,
        tags: ['infrastructure'],
        description: {
            en: 'Prettier configuration preset for Gravity UI projects.',
            ru: 'Prettier configuration preset for Gravity UI projects.',
        },
        storybookUrl: '',
        readmeUrl: 'https://raw.githubusercontent.com/gravity-ui/prettier-config/main/README.md',
        changelogUrl:
            'https://raw.githubusercontent.com/gravity-ui/prettier-config/main/CHANGELOG.md',
        mainBranch: 'main',
    },
    {
        id: 'stylelint-config',
        githubId: 'gravity-ui/stylelint-config',
        npmId: '@gravity-ui/stylelint-config',
        title: 'Stylelint Config',
        primary: false,
        landing: false,
        tags: ['infrastructure'],
        description: {
            en: 'Stylelint configuration preset for Gravity UI projects.',
            ru: 'Stylelint configuration preset for Gravity UI projects.',
        },
        storybookUrl: '',
        readmeUrl: 'https://raw.githubusercontent.com/gravity-ui/stylelint-config/main/README.md',
        changelogUrl:
            'https://raw.githubusercontent.com/gravity-ui/stylelint-config/main/CHANGELOG.md',
        mainBranch: 'main',
    },
    {
        id: 'babel-preset',
        githubId: 'gravity-ui/babel-preset',
        npmId: '@gravity-ui/babel-preset',
        title: 'Babel Preset',
        primary: false,
        landing: false,
        tags: ['infrastructure'],
        description: {
            en: 'Babel configuration preset for Gravity UI projects.',
            ru: 'Babel configuration preset for Gravity UI projects.',
        },
        storybookUrl: '',
        readmeUrl: 'https://raw.githubusercontent.com/gravity-ui/babel-preset/main/README.md',
        changelogUrl: 'https://raw.githubusercontent.com/gravity-ui/babel-preset/main/CHANGELOG.md',
        mainBranch: 'main',
    },
    {
        id: 'browserslist-config',
        githubId: 'gravity-ui/browserslist-config',
        npmId: '@gravity-ui/browserslist-config',
        title: 'Browserslist Config',
        primary: false,
        landing: false,
        tags: ['infrastructure'],
        description: {
            en: 'Browserslist confugiration preset used in our services.',
            ru: 'Browserslist confugiration preset used in our services.',
        },
        storybookUrl: '',
        readmeUrl:
            'https://raw.githubusercontent.com/gravity-ui/browserslist-config/master/README.md',
        changelogUrl:
            'https://raw.githubusercontent.com/gravity-ui/browserslist-config/master/CHANGELOG.md',
        mainBranch: 'master',
    },
];
