export const libs = [
    {
        id: 'uikit',
        title: 'UIKit',
        text: 'A wide range of easy-to-use components for creating interfaces of any complexity.',
        githubId: 'gravity-ui/uikit',
        npmId: '@gravity-ui/uikit',
        storybookUrl: 'https://preview.gravity-ui.com/uikit/',
        readmeUrl: 'https://raw.githubusercontent.com/gravity-ui/uikit/main/README.md',
    },
    {
        id: 'page-constructor',
        title: 'Page&nbsp;constructor',
        text: 'A set of stylish, functional blocks to quickly create promo and landing pages.',
        githubId: 'gravity-ui/page-constructor',
        npmId: '@gravity-ui/page-constructor',
        storybookUrl: 'https://preview.gravity-ui.com/page-constructor/',
        readmeUrl: 'https://raw.githubusercontent.com/gravity-ui/page-constructor/main/README.md',
    },
    {
        id: 'chartkit',
        title: 'ChartKit',
        text: 'A data visualization suite integrated with our design system.',
        githubId: 'gravity-ui/chartkit',
        npmId: '@gravity-ui/chartkit',
        readmeUrl: 'https://raw.githubusercontent.com/gravity-ui/chartkit/main/README.md',
    },
    {
        id: 'navigation',
        title: 'Navigation',
        text: 'A compact and extensible navigation panel for complex services.',
        githubId: 'gravity-ui/navigation',
        npmId: '@gravity-ui/navigation',
        storybookUrl: 'https://preview.gravity-ui.com/navigation/',
        readmeUrl: 'https://raw.githubusercontent.com/gravity-ui/navigation/main/README.md',
    },
    {
        id: 'yagr',
        title: 'Yagr',
        text: 'A high-performance renderer of HTML5 canvas charts, based on uPlot.',
        githubId: 'gravity-ui/yagr',
        npmId: '@gravity-ui/yagr',
        readmeUrl: 'https://raw.githubusercontent.com/gravity-ui/yagr/main/README.md',
    },
    {
        id: 'dashkit',
        title: 'DashKit',
        text: 'A grid component for building interactive dashboards.',
        githubId: 'gravity-ui/dashkit',
        npmId: '@gravity-ui/dashkit',
        readmeUrl: 'https://raw.githubusercontent.com/gravity-ui/dashkit/main/README.md',
    },
];
