name: Deploy to Yandex Cloud

on:
  workflow_run:
    workflows:
      - Build and Push Docker Image
    types:
      - completed

jobs:
  deploy:
    name: Deploy to Yandex Cloud
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: read
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.0.0

      - name: Configure AWS credentials for Terraform backend
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.STATIC_S3_KEY_ID }}
          aws-secret-access-key: ${{ secrets.STATIC_S3_SECRET_KEY }}
          aws-region: ru-central1

      - name: Get Docker image tag
        id: get_tag
        run: |
          SHA_SHORT=$(echo ${{ github.event.workflow_run.head_sha }} | cut -c1-7)
          echo "tag=${SHA_SHORT}" >> $GITHUB_OUTPUT

      - name: Terraform Init
        run: |
          cd terraform
          terraform init
        env:
          TF_VAR_yc_token: ${{ secrets.YC_TOKEN }}
          TF_VAR_yc_cloud_id: ${{ secrets.YC_CLOUD_ID }}
          TF_VAR_yc_folder_id: ${{ secrets.YC_FOLDER_ID }}
          TF_VAR_github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Terraform Plan
        run: |
          cd terraform
          terraform plan -out=tfplan
        env:
          TF_VAR_yc_token: ${{ secrets.YC_TOKEN }}
          TF_VAR_yc_cloud_id: ${{ secrets.YC_CLOUD_ID }}
          TF_VAR_yc_folder_id: ${{ secrets.YC_FOLDER_ID }}
          TF_VAR_container_image: 'ghcr.io/${{ github.repository }}:${{ steps.get_tag.outputs.tag }}'
          TF_VAR_github_token: ${{ secrets.GITHUB_TOKEN }}

      # - name: Terraform Apply
      #   run: |
      #     cd terraform
      #     terraform apply -auto-approve tfplan
      #   env:
      #     TF_VAR_yc_token: ${{ secrets.YC_TOKEN }}
      #     TF_VAR_yc_cloud_id: ${{ secrets.YC_CLOUD_ID }}
      #     TF_VAR_yc_folder_id: ${{ secrets.YC_FOLDER_ID }}
      #     TF_VAR_github_token: ${{ secrets.GITHUB_TOKEN }}
