name: Upgrade sandbox packages

on:
  workflow_dispatch:
  schedule:
    - cron: 0 12 * * 1

jobs:
  upgrade:
    permissions:
      pull-requests: write
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: Upgrade sandbox packages
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npm i @gravity-ui/uikit@latest @gravity-ui/components@latest @gravity-ui/date-components@latest @gravity-ui/icons@latest @gravity-ui/navigation@latest
          git config user.email ""
          git config user.name "Upgrade sandbox packages action"
          git checkout -b upgrade-sandbox-packages
          git add package.json package-lock.json
          export COMMIT_MESSAGE="chore(sandbox): upgrade sandbox packages"
          git commit -m "$COMMIT_MESSAGE"
          git push --set-upstream origin upgrade-sandbox-packages --force
          gh pr create --title "$COMMIT_MESSAGE" --body "" -a "imsitnikov" -a "amje" -a "korvin89" || gh pr edit --title "$COMMIT_MESSAGE" --body ""
